FROM eclipse-temurin:24-jre

WORKDIR /app

ENV NODE_DIRECTORY=/app/node
ENV PUBLIC_DIRECTORY=/app/public
ENV RMI_PORT=1099
ENV NODE_ADDRESS=rmi://localhost:${RMI_PORT}/node
ENV KNOWN_NODES=rmi://localhost:${RMI_PORT}/node
ENV PROCESSING_POWER_MULTIPLIER=1
ENV JVM_XMS=""
ENV JVM_XMX=""

ENTRYPOINT ["sh", "-c", "java ${JVM_XMS:+-Xms$JVM_XMS} ${JVM_XMX:+-Xmx$JVM_XMX} -jar javamapreduce.jar 2>&1"]

COPY target/javamapreduce.jar /app/javamapreduce.jar
